"""
Registry of American news sources — national + regional.
Each source has: name, type, url, category, lean, is_regional, region, states.
"""

# ── Helper: Google News RSS for a site ────────────────────────────────────────
def _gnews(site: str, query: str = "") -> str:
    q = f"site:{site}" + (f"+{query.replace(' ', '+')}" if query else "")
    return f"https://news.google.com/rss/search?q={q}&hl=en-US&gl=US&ceid=US:en"


SOURCES = [
    # ══════════════════════════════════════════════════════════════════════════
    # NATIONAL SOURCES
    # ══════════════════════════════════════════════════════════════════════════

    # ── Wire Services ─────────────────────────────────────────────────────────
    {
        "name": "Associated Press",
        "type": "rss",
        "url": "https://rsshub.app/apnews/topics/apf-topnews",
        "backup_url": _gnews("apnews.com"),
        "category": "wire",
        "lean": "center",
        "is_regional": False,
        "region": None,
    },
    {
        "name": "Reuters US",
        "type": "rss",
        "url": _gnews("reuters.com", "US news"),
        "category": "wire",
        "lean": "center",
        "is_regional": False,
        "region": None,
    },
    {
        "name": "UPI News",
        "type": "rss",
        "url": "https://www.upi.com/rss/news/us_news/",
        "backup_url": _gnews("upi.com"),
        "category": "wire",
        "lean": "center",
        "is_regional": False,
        "region": None,
    },

    # ── Major National Newspapers ─────────────────────────────────────────────
    {
        "name": "New York Times",
        "type": "rss",
        "url": "https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml",
        "category": "newspaper",
        "lean": "center-left",
        "is_regional": False,
        "region": None,
    },
    {
        "name": "Washington Post",
        "type": "rss",
        "url": "https://feeds.washingtonpost.com/rss/national",
        "backup_url": "https://feeds.washingtonpost.com/rss/politics",
        "category": "newspaper",
        "lean": "center-left",
        "is_regional": False,
        "region": None,
    },
    {
        "name": "Wall Street Journal",
        "type": "rss",
        "url": "https://feeds.a.dj.com/rss/WSJcomUSBusiness.xml",
        "backup_url": "https://feeds.a.dj.com/rss/RSSWorldNews.xml",
        "category": "newspaper",
        "lean": "center-right",
        "is_regional": False,
        "region": None,
    },
    {
        "name": "USA Today",
        "type": "rss",
        "url": "https://rssfeeds.usatoday.com/usatoday-NewsTopStories",
        "backup_url": _gnews("usatoday.com"),
        "category": "newspaper",
        "lean": "center",
        "is_regional": False,
        "region": None,
    },
    {
        "name": "Los Angeles Times",
        "type": "rss",
        "url": "https://www.latimes.com/rss2.0.xml",
        "backup_url": _gnews("latimes.com"),
        "category": "newspaper",
        "lean": "center-left",
        "is_regional": False,
        "region": None,
    },
    {
        "name": "Chicago Tribune",
        "type": "rss",
        "url": _gnews("chicagotribune.com"),
        "category": "newspaper",
        "lean": "center",
        "is_regional": False,
        "region": None,
    },

    # ── Cable / Broadcast News ─────────────────────────────────────────────────
    {
        "name": "CNN",
        "type": "rss",
        "url": "http://rss.cnn.com/rss/cnn_topstories.rss",
        "category": "cable_news",
        "lean": "center-left",
        "is_regional": False,
        "region": None,
    },
    {
        "name": "Fox News",
        "type": "rss",
        "url": "https://moxie.foxnews.com/google-publisher/latest.xml",
        "category": "cable_news",
        "lean": "right",
        "is_regional": False,
        "region": None,
    },
    {
        "name": "NBC News",
        "type": "rss",
        "url": "https://feeds.nbcnews.com/nbcnews/public/news",
        "category": "cable_news",
        "lean": "center-left",
        "is_regional": False,
        "region": None,
    },
    {
        "name": "CBS News",
        "type": "rss",
        "url": "https://www.cbsnews.com/latest/rss/main",
        "category": "cable_news",
        "lean": "center",
        "is_regional": False,
        "region": None,
    },
    {
        "name": "ABC News",
        "type": "rss",
        "url": "https://abcnews.go.com/abcnews/topstories",
        "category": "cable_news",
        "lean": "center",
        "is_regional": False,
        "region": None,
    },
    {
        "name": "NPR News",
        "type": "rss",
        "url": "https://feeds.npr.org/1001/rss.xml",
        "category": "cable_news",
        "lean": "center-left",
        "is_regional": False,
        "region": None,
    },
    {
        "name": "PBS NewsHour",
        "type": "rss",
        "url": "https://www.pbs.org/newshour/feeds/rss/headlines",
        "category": "cable_news",
        "lean": "center",
        "is_regional": False,
        "region": None,
    },
    {
        "name": "MSNBC",
        "type": "rss",
        "url": "https://feeds.nbcnews.com/msnbc/public/news",
        "category": "cable_news",
        "lean": "left",
        "is_regional": False,
        "region": None,
    },

    # ── Political & News Magazines ─────────────────────────────────────────────
    {
        "name": "Politico",
        "type": "rss",
        "url": "https://rss.politico.com/politics-news.xml",
        "category": "newsletter",
        "lean": "center",
        "is_regional": False,
        "region": None,
    },
    {
        "name": "The Hill",
        "type": "rss",
        "url": "https://thehill.com/feed/",
        "category": "newsletter",
        "lean": "center",
        "is_regional": False,
        "region": None,
    },
    {
        "name": "Axios",
        "type": "rss",
        "url": "https://api.axios.com/feed/",
        "category": "newsletter",
        "lean": "center",
        "is_regional": False,
        "region": None,
    },
    {
        "name": "The Atlantic",
        "type": "rss",
        "url": "https://www.theatlantic.com/feed/all/",
        "category": "magazine",
        "lean": "center-left",
        "is_regional": False,
        "region": None,
    },
    {
        "name": "National Review",
        "type": "rss",
        "url": "https://www.nationalreview.com/feed/",
        "category": "magazine",
        "lean": "right",
        "is_regional": False,
        "region": None,
    },
    {
        "name": "The New Yorker",
        "type": "rss",
        "url": "https://www.newyorker.com/feed/everything",
        "category": "magazine",
        "lean": "left",
        "is_regional": False,
        "region": None,
    },
    {
        "name": "Vox",
        "type": "rss",
        "url": "https://www.vox.com/rss/index.xml",
        "category": "magazine",
        "lean": "left",
        "is_regional": False,
        "region": None,
    },
    {
        "name": "The Economist US",
        "type": "rss",
        "url": "https://www.economist.com/united-states/rss.xml",
        "category": "magazine",
        "lean": "center",
        "is_regional": False,
        "region": None,
    },
    {
        "name": "Slate",
        "type": "rss",
        "url": "https://feeds.slate.com/slate/blogs/news_and_politics",
        "backup_url": _gnews("slate.com"),
        "category": "magazine",
        "lean": "left",
        "is_regional": False,
        "region": None,
    },
    {
        "name": "The Weekly Standard / Washington Examiner",
        "type": "rss",
        "url": "https://www.washingtonexaminer.com/section/news.rss",
        "backup_url": _gnews("washingtonexaminer.com"),
        "category": "magazine",
        "lean": "right",
        "is_regional": False,
        "region": None,
    },
    {
        "name": "The Daily Beast",
        "type": "rss",
        "url": "https://feeds.thedailybeast.com/rss/articles",
        "category": "magazine",
        "lean": "left",
        "is_regional": False,
        "region": None,
    },
    {
        "name": "HuffPost",
        "type": "rss",
        "url": "https://www.huffpost.com/section/front-page/feed",
        "category": "newsletter",
        "lean": "left",
        "is_regional": False,
        "region": None,
    },
    {
        "name": "RealClearPolitics",
        "type": "rss",
        "url": "https://feeds.feedburner.com/realclearpolitics/qlMj",
        "category": "aggregator",
        "lean": "center-right",
        "is_regional": False,
        "region": None,
    },
    {
        "name": "Newsweek",
        "type": "rss",
        "url": "https://www.newsweek.com/rss",
        "backup_url": _gnews("newsweek.com"),
        "category": "magazine",
        "lean": "center",
        "is_regional": False,
        "region": None,
    },
    {
        "name": "TIME",
        "type": "rss",
        "url": "https://time.com/feed/",
        "category": "magazine",
        "lean": "center-left",
        "is_regional": False,
        "region": None,
    },
    {
        "name": "Bloomberg Politics",
        "type": "rss",
        "url": _gnews("bloomberg.com", "US politics"),
        "category": "newspaper",
        "lean": "center",
        "is_regional": False,
        "region": None,
    },
    {
        "name": "ProPublica",
        "type": "rss",
        "url": "https://www.propublica.org/feeds/propublica/main",
        "category": "nonprofit",
        "lean": "center-left",
        "is_regional": False,
        "region": None,
    },
    {
        "name": "The Intercept",
        "type": "rss",
        "url": "https://theintercept.com/feed/?rss",
        "category": "nonprofit",
        "lean": "left",
        "is_regional": False,
        "region": None,
    },
    {
        "name": "Reason",
        "type": "rss",
        "url": "https://reason.com/latest/feed/",
        "category": "magazine",
        "lean": "libertarian",
        "is_regional": False,
        "region": None,
    },

    # ── Think Tanks ────────────────────────────────────────────────────────────
    {
        "name": "Brookings Institution",
        "type": "rss",
        "url": "https://www.brookings.edu/feed/",
        "category": "think_tank",
        "lean": "center-left",
        "is_regional": False,
        "region": None,
    },
    {
        "name": "CATO Institute",
        "type": "rss",
        "url": "https://www.cato.org/rss/recent-opeds",
        "category": "think_tank",
        "lean": "libertarian",
        "is_regional": False,
        "region": None,
    },
    {
        "name": "Heritage Foundation",
        "type": "rss",
        "url": "https://www.heritage.org/rss/all-research-and-commentary",
        "category": "think_tank",
        "lean": "right",
        "is_regional": False,
        "region": None,
    },
    {
        "name": "Center for American Progress",
        "type": "rss",
        "url": "https://www.americanprogress.org/feed/",
        "category": "think_tank",
        "lean": "left",
        "is_regional": False,
        "region": None,
    },
    {
        "name": "Council on Foreign Relations",
        "type": "rss",
        "url": "https://www.cfr.org/rss.xml",
        "category": "think_tank",
        "lean": "center",
        "is_regional": False,
        "region": None,
    },
    {
        "name": "American Enterprise Institute",
        "type": "rss",
        "url": "https://www.aei.org/feed/",
        "category": "think_tank",
        "lean": "center-right",
        "is_regional": False,
        "region": None,
    },

    # ── Government & Official ──────────────────────────────────────────────────
    {
        "name": "White House",
        "type": "rss",
        "url": "https://www.whitehouse.gov/feed/",
        "category": "government",
        "lean": "official",
        "is_regional": False,
        "region": None,
    },

    # ── Google News Aggregators ────────────────────────────────────────────────
    {
        "name": "Google News – US Headlines",
        "type": "rss",
        "url": "https://news.google.com/rss?hl=en-US&gl=US&ceid=US:en",
        "category": "aggregator",
        "lean": "mixed",
        "is_regional": False,
        "region": None,
    },
    {
        "name": "Google News – US Politics",
        "type": "rss",
        "url": "https://news.google.com/rss/topics/CAAqBwgKMJTGlgswrq2yAw?hl=en-US&gl=US&ceid=US:en",
        "category": "aggregator",
        "lean": "mixed",
        "is_regional": False,
        "region": None,
    },
    {
        "name": "Google News – Economy",
        "type": "rss",
        "url": "https://news.google.com/rss/search?q=US+economy+jobs+inflation+when:1d&hl=en-US&gl=US&ceid=US:en",
        "category": "aggregator",
        "lean": "mixed",
        "is_regional": False,
        "region": None,
    },
    {
        "name": "Google News – Immigration",
        "type": "rss",
        "url": "https://news.google.com/rss/search?q=immigration+border+deportation+when:1d&hl=en-US&gl=US&ceid=US:en",
        "category": "aggregator",
        "lean": "mixed",
        "is_regional": False,
        "region": None,
    },

    # ══════════════════════════════════════════════════════════════════════════
    # REGIONAL SOURCES — NORTHEAST
    # (ME, NH, VT, MA, RI, CT)
    # ══════════════════════════════════════════════════════════════════════════
    {
        "name": "Boston Globe",
        "type": "rss",
        "url": _gnews("bostonglobe.com"),
        "category": "regional_newspaper",
        "lean": "center-left",
        "is_regional": True,
        "region": "Northeast",
        "states": ["MA"],
    },
    {
        "name": "Boston Herald",
        "type": "rss",
        "url": "https://www.bostonherald.com/feed/",
        "backup_url": _gnews("bostonherald.com"),
        "category": "regional_newspaper",
        "lean": "center-right",
        "is_regional": True,
        "region": "Northeast",
        "states": ["MA"],
    },
    {
        "name": "Providence Journal",
        "type": "rss",
        "url": _gnews("providencejournal.com"),
        "category": "regional_newspaper",
        "lean": "center",
        "is_regional": True,
        "region": "Northeast",
        "states": ["RI"],
    },
    {
        "name": "Hartford Courant",
        "type": "rss",
        "url": _gnews("courant.com"),
        "category": "regional_newspaper",
        "lean": "center",
        "is_regional": True,
        "region": "Northeast",
        "states": ["CT"],
    },
    {
        "name": "Portland Press Herald (ME)",
        "type": "rss",
        "url": "https://www.pressherald.com/feed/",
        "backup_url": _gnews("pressherald.com"),
        "category": "regional_newspaper",
        "lean": "center",
        "is_regional": True,
        "region": "Northeast",
        "states": ["ME"],
    },
    {
        "name": "Concord Monitor (NH)",
        "type": "rss",
        "url": _gnews("concordmonitor.com"),
        "category": "regional_newspaper",
        "lean": "center",
        "is_regional": True,
        "region": "Northeast",
        "states": ["NH"],
    },
    {
        "name": "Burlington Free Press (VT)",
        "type": "rss",
        "url": _gnews("burlingtonfreepress.com"),
        "category": "regional_newspaper",
        "lean": "center",
        "is_regional": True,
        "region": "Northeast",
        "states": ["VT"],
    },
    {
        "name": "WBUR Boston",
        "type": "rss",
        "url": "https://www.wbur.org/rss/news",
        "category": "regional_broadcast",
        "lean": "center-left",
        "is_regional": True,
        "region": "Northeast",
        "states": ["MA"],
    },

    # ══════════════════════════════════════════════════════════════════════════
    # REGIONAL SOURCES — MID-ATLANTIC
    # (NY, NJ, PA, DE, MD)
    # ══════════════════════════════════════════════════════════════════════════
    {
        "name": "New York Daily News",
        "type": "rss",
        "url": "https://www.nydailynews.com/arcio/rss/category/news/",
        "backup_url": _gnews("nydailynews.com"),
        "category": "regional_newspaper",
        "lean": "center-left",
        "is_regional": True,
        "region": "Mid-Atlantic",
        "states": ["NY"],
    },
    {
        "name": "New York Post",
        "type": "rss",
        "url": "https://nypost.com/feed/",
        "category": "regional_newspaper",
        "lean": "right",
        "is_regional": True,
        "region": "Mid-Atlantic",
        "states": ["NY"],
    },
    {
        "name": "Newsday (NY)",
        "type": "rss",
        "url": _gnews("newsday.com"),
        "category": "regional_newspaper",
        "lean": "center",
        "is_regional": True,
        "region": "Mid-Atlantic",
        "states": ["NY"],
    },
    {
        "name": "Philadelphia Inquirer",
        "type": "rss",
        "url": _gnews("inquirer.com"),
        "category": "regional_newspaper",
        "lean": "center-left",
        "is_regional": True,
        "region": "Mid-Atlantic",
        "states": ["PA"],
    },
    {
        "name": "Pittsburgh Post-Gazette",
        "type": "rss",
        "url": "https://feeds.post-gazette.com/pg-news",
        "backup_url": _gnews("post-gazette.com"),
        "category": "regional_newspaper",
        "lean": "center",
        "is_regional": True,
        "region": "Mid-Atlantic",
        "states": ["PA"],
    },
    {
        "name": "Baltimore Sun",
        "type": "rss",
        "url": _gnews("baltimoresun.com"),
        "category": "regional_newspaper",
        "lean": "center-left",
        "is_regional": True,
        "region": "Mid-Atlantic",
        "states": ["MD"],
    },
    {
        "name": "NJ.com / Star-Ledger",
        "type": "rss",
        "url": "https://www.nj.com/arcio/rss/category/news/",
        "backup_url": _gnews("nj.com"),
        "category": "regional_newspaper",
        "lean": "center",
        "is_regional": True,
        "region": "Mid-Atlantic",
        "states": ["NJ"],
    },
    {
        "name": "Delaware Online",
        "type": "rss",
        "url": _gnews("delawareonline.com"),
        "category": "regional_newspaper",
        "lean": "center",
        "is_regional": True,
        "region": "Mid-Atlantic",
        "states": ["DE"],
    },
    {
        "name": "WHYY Philadelphia",
        "type": "rss",
        "url": "https://whyy.org/feed/",
        "backup_url": _gnews("whyy.org"),
        "category": "regional_broadcast",
        "lean": "center",
        "is_regional": True,
        "region": "Mid-Atlantic",
        "states": ["PA"],
    },

    # ══════════════════════════════════════════════════════════════════════════
    # REGIONAL SOURCES — SOUTHEAST
    # (VA, NC, SC, GA, FL, TN, AL, MS, LA, AR, KY, WV)
    # ══════════════════════════════════════════════════════════════════════════
    {
        "name": "Miami Herald",
        "type": "rss",
        "url": _gnews("miamiherald.com"),
        "category": "regional_newspaper",
        "lean": "center-left",
        "is_regional": True,
        "region": "Southeast",
        "states": ["FL"],
    },
    {
        "name": "Tampa Bay Times",
        "type": "rss",
        "url": "https://www.tampabay.com/arcio/rss/",
        "backup_url": _gnews("tampabay.com"),
        "category": "regional_newspaper",
        "lean": "center",
        "is_regional": True,
        "region": "Southeast",
        "states": ["FL"],
    },
    {
        "name": "Orlando Sentinel",
        "type": "rss",
        "url": _gnews("orlandosentinel.com"),
        "category": "regional_newspaper",
        "lean": "center",
        "is_regional": True,
        "region": "Southeast",
        "states": ["FL"],
    },
    {
        "name": "Atlanta Journal-Constitution",
        "type": "rss",
        "url": _gnews("ajc.com"),
        "category": "regional_newspaper",
        "lean": "center",
        "is_regional": True,
        "region": "Southeast",
        "states": ["GA"],
    },
    {
        "name": "Charlotte Observer",
        "type": "rss",
        "url": _gnews("charlotteobserver.com"),
        "category": "regional_newspaper",
        "lean": "center",
        "is_regional": True,
        "region": "Southeast",
        "states": ["NC"],
    },
    {
        "name": "Raleigh News & Observer",
        "type": "rss",
        "url": _gnews("newsobserver.com"),
        "category": "regional_newspaper",
        "lean": "center-left",
        "is_regional": True,
        "region": "Southeast",
        "states": ["NC"],
    },
    {
        "name": "Richmond Times-Dispatch",
        "type": "rss",
        "url": "https://richmond.com/search/?f=rss&t=article&c=news",
        "backup_url": _gnews("richmond.com"),
        "category": "regional_newspaper",
        "lean": "center-right",
        "is_regional": True,
        "region": "Southeast",
        "states": ["VA"],
    },
    {
        "name": "Nashville Tennessean",
        "type": "rss",
        "url": _gnews("tennessean.com"),
        "category": "regional_newspaper",
        "lean": "center",
        "is_regional": True,
        "region": "Southeast",
        "states": ["TN"],
    },
    {
        "name": "New Orleans Times-Picayune",
        "type": "rss",
        "url": _gnews("nola.com"),
        "category": "regional_newspaper",
        "lean": "center",
        "is_regional": True,
        "region": "Southeast",
        "states": ["LA"],
    },
    {
        "name": "Birmingham News / AL.com",
        "type": "rss",
        "url": "https://www.al.com/arcio/rss/category/news/",
        "backup_url": _gnews("al.com"),
        "category": "regional_newspaper",
        "lean": "center",
        "is_regional": True,
        "region": "Southeast",
        "states": ["AL"],
    },
    {
        "name": "Mississippi Clarion-Ledger",
        "type": "rss",
        "url": _gnews("clarionledger.com"),
        "category": "regional_newspaper",
        "lean": "center",
        "is_regional": True,
        "region": "Southeast",
        "states": ["MS"],
    },
    {
        "name": "Arkansas Democrat-Gazette",
        "type": "rss",
        "url": _gnews("arkansasonline.com"),
        "category": "regional_newspaper",
        "lean": "center-right",
        "is_regional": True,
        "region": "Southeast",
        "states": ["AR"],
    },
    {
        "name": "Courier-Journal (Louisville)",
        "type": "rss",
        "url": _gnews("courier-journal.com"),
        "category": "regional_newspaper",
        "lean": "center",
        "is_regional": True,
        "region": "Southeast",
        "states": ["KY"],
    },
    {
        "name": "Charleston Gazette-Mail (WV)",
        "type": "rss",
        "url": _gnews("wvgazettemail.com"),
        "category": "regional_newspaper",
        "lean": "center",
        "is_regional": True,
        "region": "Southeast",
        "states": ["WV"],
    },
    {
        "name": "WRAL News (NC)",
        "type": "rss",
        "url": "https://www.wral.com/rss/news/",
        "backup_url": _gnews("wral.com"),
        "category": "regional_broadcast",
        "lean": "center",
        "is_regional": True,
        "region": "Southeast",
        "states": ["NC"],
    },

    # ══════════════════════════════════════════════════════════════════════════
    # REGIONAL SOURCES — MIDWEST
    # (OH, IN, IL, MI, WI, MN, IA, MO)
    # ══════════════════════════════════════════════════════════════════════════
    {
        "name": "Chicago Sun-Times",
        "type": "rss",
        "url": "https://chicago.suntimes.com/rss/index.xml",
        "backup_url": _gnews("chicago.suntimes.com"),
        "category": "regional_newspaper",
        "lean": "center-left",
        "is_regional": True,
        "region": "Midwest",
        "states": ["IL"],
    },
    {
        "name": "Detroit Free Press",
        "type": "rss",
        "url": _gnews("freep.com"),
        "category": "regional_newspaper",
        "lean": "center-left",
        "is_regional": True,
        "region": "Midwest",
        "states": ["MI"],
    },
    {
        "name": "Cleveland Plain Dealer / Cleveland.com",
        "type": "rss",
        "url": "https://www.cleveland.com/arcio/rss/category/news/",
        "backup_url": _gnews("cleveland.com"),
        "category": "regional_newspaper",
        "lean": "center",
        "is_regional": True,
        "region": "Midwest",
        "states": ["OH"],
    },
    {
        "name": "Columbus Dispatch",
        "type": "rss",
        "url": _gnews("dispatch.com"),
        "category": "regional_newspaper",
        "lean": "center",
        "is_regional": True,
        "region": "Midwest",
        "states": ["OH"],
    },
    {
        "name": "Indianapolis Star",
        "type": "rss",
        "url": _gnews("indystar.com"),
        "category": "regional_newspaper",
        "lean": "center",
        "is_regional": True,
        "region": "Midwest",
        "states": ["IN"],
    },
    {
        "name": "Milwaukee Journal Sentinel",
        "type": "rss",
        "url": _gnews("jsonline.com"),
        "category": "regional_newspaper",
        "lean": "center",
        "is_regional": True,
        "region": "Midwest",
        "states": ["WI"],
    },
    {
        "name": "Minneapolis Star Tribune",
        "type": "rss",
        "url": "https://www.startribune.com/local/rss/",
        "backup_url": _gnews("startribune.com"),
        "category": "regional_newspaper",
        "lean": "center-left",
        "is_regional": True,
        "region": "Midwest",
        "states": ["MN"],
    },
    {
        "name": "Des Moines Register",
        "type": "rss",
        "url": _gnews("desmoinesregister.com"),
        "category": "regional_newspaper",
        "lean": "center",
        "is_regional": True,
        "region": "Midwest",
        "states": ["IA"],
    },
    {
        "name": "Kansas City Star",
        "type": "rss",
        "url": _gnews("kansascity.com"),
        "category": "regional_newspaper",
        "lean": "center",
        "is_regional": True,
        "region": "Midwest",
        "states": ["MO", "KS"],
    },
    {
        "name": "St. Louis Post-Dispatch",
        "type": "rss",
        "url": _gnews("stltoday.com"),
        "category": "regional_newspaper",
        "lean": "center-left",
        "is_regional": True,
        "region": "Midwest",
        "states": ["MO"],
    },
    {
        "name": "Toledo Blade",
        "type": "rss",
        "url": _gnews("toledoblade.com"),
        "category": "regional_newspaper",
        "lean": "center",
        "is_regional": True,
        "region": "Midwest",
        "states": ["OH"],
    },
    {
        "name": "Grand Rapids Press / MLive",
        "type": "rss",
        "url": "https://www.mlive.com/arcio/rss/category/news/",
        "backup_url": _gnews("mlive.com"),
        "category": "regional_newspaper",
        "lean": "center",
        "is_regional": True,
        "region": "Midwest",
        "states": ["MI"],
    },
    {
        "name": "MPR News (Minnesota)",
        "type": "rss",
        "url": "https://www.mprnews.org/rss",
        "backup_url": _gnews("mprnews.org"),
        "category": "regional_broadcast",
        "lean": "center",
        "is_regional": True,
        "region": "Midwest",
        "states": ["MN"],
    },

    # ══════════════════════════════════════════════════════════════════════════
    # REGIONAL SOURCES — GREAT PLAINS
    # (ND, SD, NE, KS, OK)
    # ══════════════════════════════════════════════════════════════════════════
    {
        "name": "Omaha World-Herald",
        "type": "rss",
        "url": _gnews("omaha.com"),
        "category": "regional_newspaper",
        "lean": "center-right",
        "is_regional": True,
        "region": "Great Plains",
        "states": ["NE"],
    },
    {
        "name": "Wichita Eagle",
        "type": "rss",
        "url": _gnews("kansas.com"),
        "category": "regional_newspaper",
        "lean": "center",
        "is_regional": True,
        "region": "Great Plains",
        "states": ["KS"],
    },
    {
        "name": "Tulsa World",
        "type": "rss",
        "url": _gnews("tulsaworld.com"),
        "category": "regional_newspaper",
        "lean": "center-right",
        "is_regional": True,
        "region": "Great Plains",
        "states": ["OK"],
    },
    {
        "name": "The Oklahoman",
        "type": "rss",
        "url": _gnews("oklahoman.com"),
        "category": "regional_newspaper",
        "lean": "center-right",
        "is_regional": True,
        "region": "Great Plains",
        "states": ["OK"],
    },
    {
        "name": "Sioux Falls Argus Leader",
        "type": "rss",
        "url": _gnews("argusleader.com"),
        "category": "regional_newspaper",
        "lean": "center",
        "is_regional": True,
        "region": "Great Plains",
        "states": ["SD"],
    },
    {
        "name": "Bismarck Tribune (ND)",
        "type": "rss",
        "url": _gnews("bismarcktribune.com"),
        "category": "regional_newspaper",
        "lean": "center-right",
        "is_regional": True,
        "region": "Great Plains",
        "states": ["ND"],
    },
    {
        "name": "Lincoln Journal Star",
        "type": "rss",
        "url": _gnews("journalstar.com"),
        "category": "regional_newspaper",
        "lean": "center",
        "is_regional": True,
        "region": "Great Plains",
        "states": ["NE"],
    },

    # ══════════════════════════════════════════════════════════════════════════
    # REGIONAL SOURCES — SOUTH / SOUTHWEST
    # (TX, NM, AZ)
    # ══════════════════════════════════════════════════════════════════════════
    {
        "name": "Dallas Morning News",
        "type": "rss",
        "url": "https://www.dallasnews.com/arcio/rss/",
        "backup_url": _gnews("dallasnews.com"),
        "category": "regional_newspaper",
        "lean": "center",
        "is_regional": True,
        "region": "South",
        "states": ["TX"],
    },
    {
        "name": "Houston Chronicle",
        "type": "rss",
        "url": _gnews("houstonchronicle.com"),
        "category": "regional_newspaper",
        "lean": "center",
        "is_regional": True,
        "region": "South",
        "states": ["TX"],
    },
    {
        "name": "San Antonio Express-News",
        "type": "rss",
        "url": _gnews("expressnews.com"),
        "category": "regional_newspaper",
        "lean": "center",
        "is_regional": True,
        "region": "South",
        "states": ["TX"],
    },
    {
        "name": "Austin American-Statesman",
        "type": "rss",
        "url": _gnews("statesman.com"),
        "category": "regional_newspaper",
        "lean": "center",
        "is_regional": True,
        "region": "South",
        "states": ["TX"],
    },
    {
        "name": "Fort Worth Star-Telegram",
        "type": "rss",
        "url": _gnews("star-telegram.com"),
        "category": "regional_newspaper",
        "lean": "center",
        "is_regional": True,
        "region": "South",
        "states": ["TX"],
    },
    {
        "name": "Texas Tribune",
        "type": "rss",
        "url": "https://www.texastribune.org/feed/",
        "category": "regional_nonprofit",
        "lean": "center",
        "is_regional": True,
        "region": "South",
        "states": ["TX"],
    },
    {
        "name": "Arizona Republic",
        "type": "rss",
        "url": _gnews("azcentral.com"),
        "category": "regional_newspaper",
        "lean": "center",
        "is_regional": True,
        "region": "South",
        "states": ["AZ"],
    },
    {
        "name": "Tucson Star",
        "type": "rss",
        "url": _gnews("tucson.com"),
        "category": "regional_newspaper",
        "lean": "center",
        "is_regional": True,
        "region": "South",
        "states": ["AZ"],
    },
    {
        "name": "Albuquerque Journal",
        "type": "rss",
        "url": _gnews("abqjournal.com"),
        "category": "regional_newspaper",
        "lean": "center",
        "is_regional": True,
        "region": "South",
        "states": ["NM"],
    },
    {
        "name": "El Paso Times",
        "type": "rss",
        "url": _gnews("elpasotimes.com"),
        "category": "regional_newspaper",
        "lean": "center",
        "is_regional": True,
        "region": "South",
        "states": ["TX"],
    },
    {
        "name": "KERA News (Texas)",
        "type": "rss",
        "url": "https://www.keranews.org/rss.xml",
        "backup_url": _gnews("keranews.org"),
        "category": "regional_broadcast",
        "lean": "center",
        "is_regional": True,
        "region": "South",
        "states": ["TX"],
    },

    # ══════════════════════════════════════════════════════════════════════════
    # REGIONAL SOURCES — MOUNTAIN WEST
    # (MT, WY, CO, UT, ID, NV)
    # ══════════════════════════════════════════════════════════════════════════
    {
        "name": "Denver Post",
        "type": "rss",
        "url": "https://www.denverpost.com/feed/",
        "backup_url": _gnews("denverpost.com"),
        "category": "regional_newspaper",
        "lean": "center",
        "is_regional": True,
        "region": "Mountain West",
        "states": ["CO"],
    },
    {
        "name": "Colorado Sun",
        "type": "rss",
        "url": "https://coloradosun.com/feed/",
        "category": "regional_nonprofit",
        "lean": "center",
        "is_regional": True,
        "region": "Mountain West",
        "states": ["CO"],
    },
    {
        "name": "Salt Lake Tribune",
        "type": "rss",
        "url": "https://www.sltrib.com/feed/",
        "backup_url": _gnews("sltrib.com"),
        "category": "regional_newspaper",
        "lean": "center-left",
        "is_regional": True,
        "region": "Mountain West",
        "states": ["UT"],
    },
    {
        "name": "Deseret News (UT)",
        "type": "rss",
        "url": "https://www.deseret.com/arc/outboundfeeds/rss/?outputType=xml",
        "backup_url": _gnews("deseret.com"),
        "category": "regional_newspaper",
        "lean": "center-right",
        "is_regional": True,
        "region": "Mountain West",
        "states": ["UT"],
    },
    {
        "name": "Las Vegas Review-Journal",
        "type": "rss",
        "url": "https://www.reviewjournal.com/feed/",
        "backup_url": _gnews("reviewjournal.com"),
        "category": "regional_newspaper",
        "lean": "right",
        "is_regional": True,
        "region": "Mountain West",
        "states": ["NV"],
    },
    {
        "name": "Las Vegas Sun",
        "type": "rss",
        "url": "https://lasvegassun.com/feeds/news/",
        "backup_url": _gnews("lasvegassun.com"),
        "category": "regional_newspaper",
        "lean": "center-left",
        "is_regional": True,
        "region": "Mountain West",
        "states": ["NV"],
    },
    {
        "name": "Billings Gazette (MT)",
        "type": "rss",
        "url": _gnews("billingsgazette.com"),
        "category": "regional_newspaper",
        "lean": "center-right",
        "is_regional": True,
        "region": "Mountain West",
        "states": ["MT"],
    },
    {
        "name": "Idaho Statesman",
        "type": "rss",
        "url": _gnews("idahostatesman.com"),
        "category": "regional_newspaper",
        "lean": "center",
        "is_regional": True,
        "region": "Mountain West",
        "states": ["ID"],
    },
    {
        "name": "Wyoming Tribune Eagle",
        "type": "rss",
        "url": _gnews("wyomingnews.com"),
        "category": "regional_newspaper",
        "lean": "center-right",
        "is_regional": True,
        "region": "Mountain West",
        "states": ["WY"],
    },
    {
        "name": "CPR News (Colorado)",
        "type": "rss",
        "url": "https://www.cpr.org/feed/",
        "backup_url": _gnews("cpr.org"),
        "category": "regional_broadcast",
        "lean": "center",
        "is_regional": True,
        "region": "Mountain West",
        "states": ["CO"],
    },

    # ══════════════════════════════════════════════════════════════════════════
    # REGIONAL SOURCES — WEST COAST
    # (CA, OR, WA, AK, HI)
    # ══════════════════════════════════════════════════════════════════════════
    {
        "name": "San Francisco Chronicle",
        "type": "rss",
        "url": "https://www.sfchronicle.com/feed/sfgate/rss-feed/",
        "backup_url": _gnews("sfchronicle.com"),
        "category": "regional_newspaper",
        "lean": "center-left",
        "is_regional": True,
        "region": "West Coast",
        "states": ["CA"],
    },
    {
        "name": "Sacramento Bee",
        "type": "rss",
        "url": _gnews("sacbee.com"),
        "category": "regional_newspaper",
        "lean": "center-left",
        "is_regional": True,
        "region": "West Coast",
        "states": ["CA"],
    },
    {
        "name": "San Diego Union-Tribune",
        "type": "rss",
        "url": _gnews("sandiegouniontribune.com"),
        "category": "regional_newspaper",
        "lean": "center",
        "is_regional": True,
        "region": "West Coast",
        "states": ["CA"],
    },
    {
        "name": "Orange County Register",
        "type": "rss",
        "url": "https://www.ocregister.com/feed/",
        "backup_url": _gnews("ocregister.com"),
        "category": "regional_newspaper",
        "lean": "center-right",
        "is_regional": True,
        "region": "West Coast",
        "states": ["CA"],
    },
    {
        "name": "Seattle Times",
        "type": "rss",
        "url": "https://www.seattletimes.com/feed/",
        "backup_url": _gnews("seattletimes.com"),
        "category": "regional_newspaper",
        "lean": "center-left",
        "is_regional": True,
        "region": "West Coast",
        "states": ["WA"],
    },
    {
        "name": "Oregonian / OregonLive",
        "type": "rss",
        "url": "https://www.oregonlive.com/arcio/rss/category/news/",
        "backup_url": _gnews("oregonlive.com"),
        "category": "regional_newspaper",
        "lean": "center",
        "is_regional": True,
        "region": "West Coast",
        "states": ["OR"],
    },
    {
        "name": "Anchorage Daily News",
        "type": "rss",
        "url": "https://www.adn.com/feed/",
        "backup_url": _gnews("adn.com"),
        "category": "regional_newspaper",
        "lean": "center",
        "is_regional": True,
        "region": "West Coast",
        "states": ["AK"],
    },
    {
        "name": "Honolulu Star-Advertiser",
        "type": "rss",
        "url": _gnews("staradvertiser.com"),
        "category": "regional_newspaper",
        "lean": "center",
        "is_regional": True,
        "region": "West Coast",
        "states": ["HI"],
    },
    {
        "name": "Spokane Spokesman-Review",
        "type": "rss",
        "url": "https://www.spokesman.com/feeds/headlines/",
        "backup_url": _gnews("spokesman.com"),
        "category": "regional_newspaper",
        "lean": "center-right",
        "is_regional": True,
        "region": "West Coast",
        "states": ["WA"],
    },
    {
        "name": "KQED (San Francisco)",
        "type": "rss",
        "url": "https://www.kqed.org/news/feed/rss2",
        "backup_url": _gnews("kqed.org"),
        "category": "regional_broadcast",
        "lean": "center-left",
        "is_regional": True,
        "region": "West Coast",
        "states": ["CA"],
    },
    {
        "name": "KUOW (Seattle)",
        "type": "rss",
        "url": "https://www.kuow.org/rss.xml",
        "backup_url": _gnews("kuow.org"),
        "category": "regional_broadcast",
        "lean": "center",
        "is_regional": True,
        "region": "West Coast",
        "states": ["WA"],
    },
    {
        "name": "CalMatters",
        "type": "rss",
        "url": "https://calmatters.org/feed/",
        "category": "regional_nonprofit",
        "lean": "center",
        "is_regional": True,
        "region": "West Coast",
        "states": ["CA"],
    },

    # ══════════════════════════════════════════════════════════════════════════
    # ADDITIONAL REGIONAL NONPROFITS & INVESTIGATIVE
    # ══════════════════════════════════════════════════════════════════════════
    {
        "name": "The Nevada Independent",
        "type": "rss",
        "url": "https://thenevadaindependent.com/feed/",
        "backup_url": _gnews("thenevadaindependent.com"),
        "category": "regional_nonprofit",
        "lean": "center",
        "is_regional": True,
        "region": "Mountain West",
        "states": ["NV"],
    },
    {
        "name": "The Colorado Independent",
        "type": "rss",
        "url": _gnews("coloradoindependent.com"),
        "category": "regional_nonprofit",
        "lean": "center",
        "is_regional": True,
        "region": "Mountain West",
        "states": ["CO"],
    },
    {
        "name": "MinnPost (Minnesota)",
        "type": "rss",
        "url": "https://www.minnpost.com/rss/all",
        "backup_url": _gnews("minnpost.com"),
        "category": "regional_nonprofit",
        "lean": "center-left",
        "is_regional": True,
        "region": "Midwest",
        "states": ["MN"],
    },
    {
        "name": "Wisconsin Watch",
        "type": "rss",
        "url": "https://wisconsinwatch.org/feed/",
        "backup_url": _gnews("wisconsinwatch.org"),
        "category": "regional_nonprofit",
        "lean": "center",
        "is_regional": True,
        "region": "Midwest",
        "states": ["WI"],
    },
    {
        "name": "Virginia Mercury",
        "type": "rss",
        "url": "https://virginiamercury.com/feed/",
        "backup_url": _gnews("virginiamercury.com"),
        "category": "regional_nonprofit",
        "lean": "center",
        "is_regional": True,
        "region": "Southeast",
        "states": ["VA"],
    },
    {
        "name": "Georgia Recorder",
        "type": "rss",
        "url": "https://georgiarecorder.com/feed/",
        "backup_url": _gnews("georgiarecorder.com"),
        "category": "regional_nonprofit",
        "lean": "center",
        "is_regional": True,
        "region": "Southeast",
        "states": ["GA"],
    },
    {
        "name": "Michigan Advance",
        "type": "rss",
        "url": "https://michiganadvance.com/feed/",
        "backup_url": _gnews("michiganadvance.com"),
        "category": "regional_nonprofit",
        "lean": "center-left",
        "is_regional": True,
        "region": "Midwest",
        "states": ["MI"],
    },
    {
        "name": "Ohio Capital Journal",
        "type": "rss",
        "url": "https://ohiocapitaljournal.com/feed/",
        "backup_url": _gnews("ohiocapitaljournal.com"),
        "category": "regional_nonprofit",
        "lean": "center",
        "is_regional": True,
        "region": "Midwest",
        "states": ["OH"],
    },
    {
        "name": "NC Newsline",
        "type": "rss",
        "url": "https://ncnewsline.com/feed/",
        "backup_url": _gnews("ncnewsline.com"),
        "category": "regional_nonprofit",
        "lean": "center",
        "is_regional": True,
        "region": "Southeast",
        "states": ["NC"],
    },
    {
        "name": "Louisiana Illuminator",
        "type": "rss",
        "url": "https://lailluminator.com/feed/",
        "backup_url": _gnews("lailluminator.com"),
        "category": "regional_nonprofit",
        "lean": "center",
        "is_regional": True,
        "region": "Southeast",
        "states": ["LA"],
    },
    {
        "name": "New Hampshire Bulletin",
        "type": "rss",
        "url": "https://newhampshirebulletin.com/feed/",
        "backup_url": _gnews("newhampshirebulletin.com"),
        "category": "regional_nonprofit",
        "lean": "center",
        "is_regional": True,
        "region": "Northeast",
        "states": ["NH"],
    },
    {
        "name": "Pennsylvania Capital-Star",
        "type": "rss",
        "url": "https://www.penncapital-star.com/feed/",
        "backup_url": _gnews("penncapital-star.com"),
        "category": "regional_nonprofit",
        "lean": "center",
        "is_regional": True,
        "region": "Mid-Atlantic",
        "states": ["PA"],
    },
    {
        "name": "Maryland Matters",
        "type": "rss",
        "url": "https://www.marylandmatters.org/feed/",
        "backup_url": _gnews("marylandmatters.org"),
        "category": "regional_nonprofit",
        "lean": "center",
        "is_regional": True,
        "region": "Mid-Atlantic",
        "states": ["MD"],
    },
    {
        "name": "New Jersey Monitor",
        "type": "rss",
        "url": "https://newjerseymonitor.com/feed/",
        "backup_url": _gnews("newjerseymonitor.com"),
        "category": "regional_nonprofit",
        "lean": "center",
        "is_regional": True,
        "region": "Mid-Atlantic",
        "states": ["NJ"],
    },
    {
        "name": "Arizona Mirror",
        "type": "rss",
        "url": "https://azmirror.com/feed/",
        "backup_url": _gnews("azmirror.com"),
        "category": "regional_nonprofit",
        "lean": "center",
        "is_regional": True,
        "region": "South",
        "states": ["AZ"],
    },
    {
        "name": "Iowa Capital Dispatch",
        "type": "rss",
        "url": "https://iowacapitaldispatch.com/feed/",
        "backup_url": _gnews("iowacapitaldispatch.com"),
        "category": "regional_nonprofit",
        "lean": "center",
        "is_regional": True,
        "region": "Midwest",
        "states": ["IA"],
    },
    {
        "name": "Kansas Reflector",
        "type": "rss",
        "url": "https://kansasreflector.com/feed/",
        "backup_url": _gnews("kansasreflector.com"),
        "category": "regional_nonprofit",
        "lean": "center",
        "is_regional": True,
        "region": "Great Plains",
        "states": ["KS"],
    },
    {
        "name": "Missouri Independent",
        "type": "rss",
        "url": "https://missouriindependent.com/feed/",
        "backup_url": _gnews("missouriindependent.com"),
        "category": "regional_nonprofit",
        "lean": "center",
        "is_regional": True,
        "region": "Midwest",
        "states": ["MO"],
    },
    {
        "name": "Tennessee Lookout",
        "type": "rss",
        "url": "https://tennesseelookout.com/feed/",
        "backup_url": _gnews("tennesseelookout.com"),
        "category": "regional_nonprofit",
        "lean": "center",
        "is_regional": True,
        "region": "Southeast",
        "states": ["TN"],
    },
    {
        "name": "Indiana Capital Chronicle",
        "type": "rss",
        "url": "https://indianacapitalchronicle.com/feed/",
        "backup_url": _gnews("indianacapitalchronicle.com"),
        "category": "regional_nonprofit",
        "lean": "center",
        "is_regional": True,
        "region": "Midwest",
        "states": ["IN"],
    },
    {
        "name": "Mississippi Today",
        "type": "rss",
        "url": "https://mississippitoday.org/feed/",
        "backup_url": _gnews("mississippitoday.org"),
        "category": "regional_nonprofit",
        "lean": "center",
        "is_regional": True,
        "region": "Southeast",
        "states": ["MS"],
    },
    {
        "name": "Oklahoma Watch",
        "type": "rss",
        "url": "https://oklahomawatch.org/feed/",
        "backup_url": _gnews("oklahomawatch.org"),
        "category": "regional_nonprofit",
        "lean": "center",
        "is_regional": True,
        "region": "Great Plains",
        "states": ["OK"],
    },
    {
        "name": "Idaho Capital Sun",
        "type": "rss",
        "url": "https://idahocapitalsun.com/feed/",
        "backup_url": _gnews("idahocapitalsun.com"),
        "category": "regional_nonprofit",
        "lean": "center",
        "is_regional": True,
        "region": "Mountain West",
        "states": ["ID"],
    },
    {
        "name": "Montana Free Press",
        "type": "rss",
        "url": "https://montanafreepress.org/feed/",
        "backup_url": _gnews("montanafreepress.org"),
        "category": "regional_nonprofit",
        "lean": "center",
        "is_regional": True,
        "region": "Mountain West",
        "states": ["MT"],
    },
    {
        "name": "Wyoming Tribune Eagle",
        "type": "rss",
        "url": _gnews("wyomingnews.com"),
        "category": "regional_newspaper",
        "lean": "center-right",
        "is_regional": True,
        "region": "Mountain West",
        "states": ["WY"],
    },
    {
        "name": "Alaska Beacon",
        "type": "rss",
        "url": "https://alaskabeacon.com/feed/",
        "backup_url": _gnews("alaskabeacon.com"),
        "category": "regional_nonprofit",
        "lean": "center",
        "is_regional": True,
        "region": "West Coast",
        "states": ["AK"],
    },
    {
        "name": "New Mexico Political Report",
        "type": "rss",
        "url": "https://nmpoliticalreport.com/feed/",
        "backup_url": _gnews("nmpoliticalreport.com"),
        "category": "regional_nonprofit",
        "lean": "center",
        "is_regional": True,
        "region": "South",
        "states": ["NM"],
    },
    {
        "name": "Connecticut Mirror",
        "type": "rss",
        "url": "https://ctmirror.org/feed/",
        "backup_url": _gnews("ctmirror.org"),
        "category": "regional_nonprofit",
        "lean": "center",
        "is_regional": True,
        "region": "Northeast",
        "states": ["CT"],
    },
    {
        "name": "Rhode Island Current",
        "type": "rss",
        "url": "https://rhodeislandcurrent.com/feed/",
        "backup_url": _gnews("rhodeislandcurrent.com"),
        "category": "regional_nonprofit",
        "lean": "center",
        "is_regional": True,
        "region": "Northeast",
        "states": ["RI"],
    },
    {
        "name": "Maine Morning Star",
        "type": "rss",
        "url": "https://mainemorningstar.com/feed/",
        "backup_url": _gnews("mainemorningstar.com"),
        "category": "regional_nonprofit",
        "lean": "center",
        "is_regional": True,
        "region": "Northeast",
        "states": ["ME"],
    },
    {
        "name": "Vermont Digger",
        "type": "rss",
        "url": "https://vtdigger.org/feed/",
        "backup_url": _gnews("vtdigger.org"),
        "category": "regional_nonprofit",
        "lean": "center",
        "is_regional": True,
        "region": "Northeast",
        "states": ["VT"],
    },
    {
        "name": "South Carolina Daily Gazette",
        "type": "rss",
        "url": "https://scdailygazette.com/feed/",
        "backup_url": _gnews("scdailygazette.com"),
        "category": "regional_nonprofit",
        "lean": "center",
        "is_regional": True,
        "region": "Southeast",
        "states": ["SC"],
    },
    {
        "name": "West Virginia Watch",
        "type": "rss",
        "url": "https://wvwatch.com/feed/",
        "backup_url": _gnews("wvwatch.com"),
        "category": "regional_nonprofit",
        "lean": "center",
        "is_regional": True,
        "region": "Southeast",
        "states": ["WV"],
    },
    {
        "name": "Kentucky Lantern",
        "type": "rss",
        "url": "https://kentuckylantern.com/feed/",
        "backup_url": _gnews("kentuckylantern.com"),
        "category": "regional_nonprofit",
        "lean": "center",
        "is_regional": True,
        "region": "Southeast",
        "states": ["KY"],
    },
    {
        "name": "Alabama Reflector",
        "type": "rss",
        "url": "https://alabamareflector.com/feed/",
        "backup_url": _gnews("alabamareflector.com"),
        "category": "regional_nonprofit",
        "lean": "center",
        "is_regional": True,
        "region": "Southeast",
        "states": ["AL"],
    },
    {
        "name": "Arkansas Advocate",
        "type": "rss",
        "url": "https://arkansasadvocate.com/feed/",
        "backup_url": _gnews("arkansasadvocate.com"),
        "category": "regional_nonprofit",
        "lean": "center",
        "is_regional": True,
        "region": "Southeast",
        "states": ["AR"],
    },
    {
        "name": "Nebraska Examiner",
        "type": "rss",
        "url": "https://nebraskaexaminer.com/feed/",
        "backup_url": _gnews("nebraskaexaminer.com"),
        "category": "regional_nonprofit",
        "lean": "center",
        "is_regional": True,
        "region": "Great Plains",
        "states": ["NE"],
    },
    {
        "name": "North Dakota Monitor",
        "type": "rss",
        "url": "https://northdakotamonitor.com/feed/",
        "backup_url": _gnews("northdakotamonitor.com"),
        "category": "regional_nonprofit",
        "lean": "center",
        "is_regional": True,
        "region": "Great Plains",
        "states": ["ND"],
    },
    {
        "name": "South Dakota Searchlight",
        "type": "rss",
        "url": "https://southdakotasearchlight.com/feed/",
        "backup_url": _gnews("southdakotasearchlight.com"),
        "category": "regional_nonprofit",
        "lean": "center",
        "is_regional": True,
        "region": "Great Plains",
        "states": ["SD"],
    },
    {
        "name": "Utah News Dispatch",
        "type": "rss",
        "url": "https://utahnewsdispatch.com/feed/",
        "backup_url": _gnews("utahnewsdispatch.com"),
        "category": "regional_nonprofit",
        "lean": "center",
        "is_regional": True,
        "region": "Mountain West",
        "states": ["UT"],
    },
    {
        "name": "New Mexico In Depth",
        "type": "rss",
        "url": "https://nminpolitics.com/feed/",
        "backup_url": _gnews("nminpolitics.com"),
        "category": "regional_nonprofit",
        "lean": "center",
        "is_regional": True,
        "region": "South",
        "states": ["NM"],
    },
    {
        "name": "Oregon Capital Chronicle",
        "type": "rss",
        "url": "https://oregoncapitalchronicle.com/feed/",
        "backup_url": _gnews("oregoncapitalchronicle.com"),
        "category": "regional_nonprofit",
        "lean": "center",
        "is_regional": True,
        "region": "West Coast",
        "states": ["OR"],
    },
    {
        "name": "Washington State Standard",
        "type": "rss",
        "url": "https://washingtonstatestandard.com/feed/",
        "backup_url": _gnews("washingtonstatestandard.com"),
        "category": "regional_nonprofit",
        "lean": "center",
        "is_regional": True,
        "region": "West Coast",
        "states": ["WA"],
    },
    {
        "name": "Hawaii Tribune-Herald",
        "type": "rss",
        "url": _gnews("hawaiitribune-herald.com"),
        "category": "regional_newspaper",
        "lean": "center",
        "is_regional": True,
        "region": "West Coast",
        "states": ["HI"],
    },
]

# ── Metadata ───────────────────────────────────────────────────────────────────

CATEGORY_LABELS = {
    "wire": "Wire Service",
    "newspaper": "Major Newspaper",
    "cable_news": "Cable/Broadcast News",
    "newsletter": "Political Newsletter",
    "aggregator": "News Aggregator",
    "magazine": "Magazine / Long-Form",
    "think_tank": "Think Tank",
    "podcast": "Podcast",
    "government": "Government / Official",
    "nonprofit": "National Nonprofit",
    "regional_newspaper": "Regional Newspaper",
    "regional_broadcast": "Regional Broadcast",
    "regional_nonprofit": "Regional Nonprofit News",
}

LEAN_LABELS = {
    "center": "Center",
    "center-left": "Center-Left",
    "center-right": "Center-Right",
    "left": "Left",
    "right": "Right",
    "libertarian": "Libertarian",
    "official": "Official",
    "mixed": "Mixed",
}

REGIONS = [
    "Northeast",
    "Mid-Atlantic",
    "Southeast",
    "Midwest",
    "Great Plains",
    "South",
    "Mountain West",
    "West Coast",
]

REGION_STATES = {
    "Northeast": ["ME", "NH", "VT", "MA", "RI", "CT"],
    "Mid-Atlantic": ["NY", "NJ", "PA", "DE", "MD"],
    "Southeast": ["VA", "WV", "KY", "NC", "SC", "GA", "FL", "TN", "AL", "MS", "LA", "AR"],
    "Midwest": ["OH", "IN", "IL", "MI", "WI", "MN", "IA", "MO"],
    "Great Plains": ["ND", "SD", "NE", "KS", "OK"],
    "South": ["TX", "NM", "AZ"],
    "Mountain West": ["MT", "WY", "CO", "UT", "ID", "NV"],
    "West Coast": ["CA", "OR", "WA", "AK", "HI"],
}
