"""
Registry of American news, newsletter, podcast, and think tank sources.
Each source has: name, type, url(s), political lean (for perspective analysis), category.
"""

SOURCES = [
    # ── Major Wire Services & Newspapers ──────────────────────────────
    {
        "name": "Associated Press",
        "type": "rss",
        "url": "https://rsshub.app/apnews/topics/politics",
        "backup_url": "https://news.google.com/rss/search?q=site:apnews.com+politics&hl=en-US&gl=US&ceid=US:en",
        "category": "wire",
        "lean": "center",
    },
    {
        "name": "Reuters US",
        "type": "rss",
        "url": "https://news.google.com/rss/search?q=site:reuters.com+US+politics&hl=en-US&gl=US&ceid=US:en",
        "category": "wire",
        "lean": "center",
    },
    {
        "name": "New York Times - Politics",
        "type": "rss",
        "url": "https://rss.nytimes.com/services/xml/rss/nyt/Politics.xml",
        "category": "newspaper",
        "lean": "center-left",
    },
    {
        "name": "Washington Post - Politics",
        "type": "rss",
        "url": "https://feeds.washingtonpost.com/rss/politics",
        "category": "newspaper",
        "lean": "center-left",
    },
    {
        "name": "Wall Street Journal - US",
        "type": "rss",
        "url": "https://feeds.a.dj.com/rss/RSSWorldNews.xml",
        "category": "newspaper",
        "lean": "center-right",
    },
    {
        "name": "USA Today - News",
        "type": "rss",
        "url": "https://news.google.com/rss/search?q=site:usatoday.com+politics&hl=en-US&gl=US&ceid=US:en",
        "category": "newspaper",
        "lean": "center",
    },
    # ── Cable / Broadcast News ────────────────────────────────────────
    {
        "name": "CNN Politics",
        "type": "rss",
        "url": "http://rss.cnn.com/rss/cnn_allpolitics.rss",
        "category": "cable_news",
        "lean": "center-left",
    },
    {
        "name": "Fox News - Politics",
        "type": "rss",
        "url": "https://moxie.foxnews.com/google-publisher/politics.xml",
        "category": "cable_news",
        "lean": "right",
    },
    {
        "name": "MSNBC / NBC News",
        "type": "rss",
        "url": "https://feeds.nbcnews.com/nbcnews/public/politics",
        "category": "cable_news",
        "lean": "left",
    },
    {
        "name": "CBS News - Politics",
        "type": "rss",
        "url": "https://www.cbsnews.com/latest/rss/politics",
        "category": "cable_news",
        "lean": "center",
    },
    {
        "name": "ABC News - Politics",
        "type": "rss",
        "url": "https://abcnews.go.com/abcnews/politicsheadlines",
        "category": "cable_news",
        "lean": "center",
    },
    # ── Political Newsletters & Aggregators ───────────────────────────
    {
        "name": "Politico",
        "type": "rss",
        "url": "https://rss.politico.com/politics-news.xml",
        "category": "newsletter",
        "lean": "center",
    },
    {
        "name": "The Hill",
        "type": "rss",
        "url": "https://thehill.com/feed/",
        "category": "newsletter",
        "lean": "center",
    },
    {
        "name": "Axios",
        "type": "rss",
        "url": "https://api.axios.com/feed/",
        "category": "newsletter",
        "lean": "center",
    },
    {
        "name": "RealClearPolitics",
        "type": "rss",
        "url": "https://feeds.feedburner.com/realclearpolitics/qlMj",
        "category": "aggregator",
        "lean": "center-right",
    },
    {
        "name": "The Daily Beast",
        "type": "rss",
        "url": "https://feeds.thedailybeast.com/rss/articles",
        "category": "newsletter",
        "lean": "left",
    },
    {
        "name": "HuffPost Politics",
        "type": "rss",
        "url": "https://www.huffpost.com/section/politics/feed",
        "category": "newsletter",
        "lean": "left",
    },
    # ── Magazines & Long-Form ─────────────────────────────────────────
    {
        "name": "The Atlantic",
        "type": "rss",
        "url": "https://www.theatlantic.com/feed/channel/politics/",
        "category": "magazine",
        "lean": "center-left",
    },
    {
        "name": "National Review",
        "type": "rss",
        "url": "https://www.nationalreview.com/feed/",
        "category": "magazine",
        "lean": "right",
    },
    {
        "name": "The New Yorker - News",
        "type": "rss",
        "url": "https://www.newyorker.com/feed/news",
        "category": "magazine",
        "lean": "left",
    },
    {
        "name": "Vox",
        "type": "rss",
        "url": "https://www.vox.com/rss/politics/index.xml",
        "category": "magazine",
        "lean": "left",
    },
    {
        "name": "The Economist - US",
        "type": "rss",
        "url": "https://www.economist.com/united-states/rss.xml",
        "category": "magazine",
        "lean": "center",
    },
    # ── Think Tanks ───────────────────────────────────────────────────
    {
        "name": "Brookings Institution",
        "type": "rss",
        "url": "https://www.brookings.edu/feed/",
        "category": "think_tank",
        "lean": "center-left",
    },
    {
        "name": "CATO Institute",
        "type": "rss",
        "url": "https://www.cato.org/rss/recent-opeds",
        "category": "think_tank",
        "lean": "libertarian",
    },
    {
        "name": "Heritage Foundation",
        "type": "rss",
        "url": "https://www.heritage.org/rss/all-research-and-commentary",
        "category": "think_tank",
        "lean": "right",
    },
    {
        "name": "Center for American Progress",
        "type": "rss",
        "url": "https://www.americanprogress.org/feed/",
        "category": "think_tank",
        "lean": "left",
    },
    {
        "name": "Council on Foreign Relations",
        "type": "rss",
        "url": "https://www.cfr.org/rss.xml",
        "category": "think_tank",
        "lean": "center",
    },
    {
        "name": "American Enterprise Institute",
        "type": "rss",
        "url": "https://www.aei.org/feed/",
        "category": "think_tank",
        "lean": "center-right",
    },
    # ── Podcast Summaries (RSS feeds of shows) ────────────────────────
    {
        "name": "NPR Politics Podcast",
        "type": "rss",
        "url": "https://feeds.npr.org/510310/podcast.xml",
        "category": "podcast",
        "lean": "center",
    },
    {
        "name": "The Daily (NYT)",
        "type": "rss",
        "url": "https://feeds.simplecast.com/54nAGcIl",
        "category": "podcast",
        "lean": "center-left",
    },
    {
        "name": "Pod Save America",
        "type": "rss",
        "url": "https://feeds.megaphone.fm/pod-save-america",
        "category": "podcast",
        "lean": "left",
    },
    {
        "name": "The Ben Shapiro Show",
        "type": "rss",
        "url": "https://feeds.megaphone.fm/WWO3519750118",
        "category": "podcast",
        "lean": "right",
    },
    {
        "name": "FiveThirtyEight Politics",
        "type": "rss",
        "url": "https://feeds.megaphone.fm/ESP4810498498",
        "category": "podcast",
        "lean": "center",
    },
    {
        "name": "Up First (NPR)",
        "type": "rss",
        "url": "https://feeds.npr.org/510318/podcast.xml",
        "category": "podcast",
        "lean": "center",
    },
    # ── Government / Official ─────────────────────────────────────────
    {
        "name": "White House Briefing Room",
        "type": "rss",
        "url": "https://www.whitehouse.gov/feed/",
        "category": "government",
        "lean": "official",
    },
    {
        "name": "Congressional Record (GovInfo)",
        "type": "rss",
        "url": "https://www.govinfo.gov/rss/crec.xml",
        "category": "government",
        "lean": "official",
    },
    # ── Google News Catchall for US Politics ──────────────────────────
    {
        "name": "Google News - US Politics",
        "type": "rss",
        "url": "https://news.google.com/rss/topics/CAAqBwgKMJTGlgswrq2yAw?hl=en-US&gl=US&ceid=US:en",
        "category": "aggregator",
        "lean": "mixed",
    },
    {
        "name": "Google News - US Headlines",
        "type": "rss",
        "url": "https://news.google.com/rss?hl=en-US&gl=US&ceid=US:en",
        "category": "aggregator",
        "lean": "mixed",
    },
    {
        "name": "Google News - Congress",
        "type": "rss",
        "url": "https://news.google.com/rss/search?q=congress+senate+house+bill+vote+when:1d&hl=en-US&gl=US&ceid=US:en",
        "category": "aggregator",
        "lean": "mixed",
    },
    {
        "name": "Google News - White House",
        "type": "rss",
        "url": "https://news.google.com/rss/search?q=white+house+president+executive+order+when:1d&hl=en-US&gl=US&ceid=US:en",
        "category": "aggregator",
        "lean": "mixed",
    },
    {
        "name": "Google News - Supreme Court",
        "type": "rss",
        "url": "https://news.google.com/rss/search?q=supreme+court+ruling+decision+when:1d&hl=en-US&gl=US&ceid=US:en",
        "category": "aggregator",
        "lean": "mixed",
    },
]

# Category display labels
CATEGORY_LABELS = {
    "wire": "Wire Service",
    "newspaper": "Major Newspaper",
    "cable_news": "Cable/Broadcast News",
    "newsletter": "Political Newsletter",
    "aggregator": "News Aggregator",
    "magazine": "Magazine / Long-Form",
    "think_tank": "Think Tank",
    "podcast": "Podcast",
    "government": "Government / Official",
}

LEAN_LABELS = {
    "center": "Center",
    "center-left": "Center-Left",
    "center-right": "Center-Right",
    "left": "Left",
    "right": "Right",
    "libertarian": "Libertarian",
    "official": "Official",
    "mixed": "Mixed",
}
